import React, { Component } from 'react';
import { connect } from 'react-redux';
import PropType from 'prop-types';
import {
  StyleSheet,
  View,
  KeyboardAvoidingView,
  TextInput as NativeTextInput,
  TouchableOpacity,
  Image,
} from 'react-native';
import {
  Headline, TextInput, Button, HelperText, Title, Text,
} from 'react-native-paper';
import { ImagePicker } from 'expo';
import { selectApi } from '../ducks/api';
import { saveUsername, saveUserProfilePicture } from '../ducks/user';
import Table from '../middlewares/Api/Table';

const styles = StyleSheet.create({
  content: {},
  headline: {
    marginBottom: 5,
  },
  inputContainer: {
    width: '100%',
    paddingHorizontal: 30,
  },
  loginButton: {
    marginTop: 8,
  },
});

const extractor = state => ({
  api: selectApi(state),
});

const dispatcher = dispatch => ({
  changeProfilePicture: (id, b64img) => dispatch(saveUserProfilePicture(id, b64img)),
  changeUsername: (id, username) => dispatch(saveUsername(id, username)),
});

class PreferencesScreen extends Component {
  static propTypes = {
    navigation: PropType.objectOf(PropType.any).isRequired,
  };

  constructor() {
    super();
    this.state = {};
  }

  render() {
    return (
      <KeyboardAvoidingView style={styles.content} behavior="padding">
        <View style={{
          display: 'flex',
          flexDirection: 'row',
          width: '100%',
          alignItems: 'center',
        }}
        >
          <Title style={styles.headline}>How to create an account</Title>
          <Text>
            You need to create an account on Airtable before using Kanbord.
            This will no longer be required in the next version. We're sorry for the inconvenience.
          </Text>
          <Text>1. Go to airtable.com and create an account</Text>
          <Text>2. Once your account is created, create a new base</Text>
          <Text>3. In the new base, create 3 tables</Text>
          <Text>a. Meta, with two columns Name(String) and Value(String)</Text>
          <Text>b. Types, with four columns Name (String), Description (String), Fields(String), CreatedAt (Created Time)</Text>
          <Text>c. Database, with two columns Name(String), Type(Reference To Type)</Text>
          <Text>Once you have Airtable set up, go to the API documentation automatically generated by airtable</Text>
          <Text>Find your airtable base id and airtable api key, you can now use these in the login screen</Text>
        </View>
      </KeyboardAvoidingView>
    );
  }
}

const ConnectedPreferencesScreen = connect(extractor, dispatcher)(PreferencesScreen);
export default ConnectedPreferencesScreen;
